language: java
jdk:
  - oraclejdk8
sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/  
    - $HOME/.m2  
script:
  - ./gradlew clean
  
deploy:
  - provider: heroku
    api_key: 744fff7d-5617-49c1-a691-e0aa1473a891
    app: parking-lot-backend-app 
    on:
      branch: master 
        
  - provider: heroku
    api_key: 02ad66a3-fa5a-4f4a-a0c2-1542413b1246
    app: parking-lot-backend-prod
    on:
      branch: prod   
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
on_start: false     # default: false
