INSERT INTO AUTHORITY(id,name) VALUES(9991,'ROLE_EMPLOYEE');
INSERT INTO AUTHORITY(id,name) VALUES(9992,'ROLE_PARKING_CLERK');
INSERT INTO AUTHORITY(id,name) VALUES(9993,'ROLE_MANAGER');
INSERT INTO AUTHORITY(id,name) VALUES(9994,'ROLE_HR');
INSERT INTO AUTHORITY(id,name) VALUES(9999,'ROLE_ADMIN');